import { useMemo, useState } from 'react';
import { Button, Card, Input, Select } from '../ui';
import { exportAuditLogs, getAuditLogs, type AuditSeverity } from '../../utils/auditLog';

const download = (name: string, content: string, type = 'application/json') => { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); };
export const AuditLogPanel = () => {
  const [query, setQuery] = useState(''); const [role, setRole] = useState(''); const [severity, setSeverity] = useState(''); const [action, setAction] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('');
  const filter = { search: query, role, severity, action, from, to };
  const logs = useMemo(() => getAuditLogs(filter), [query, role, severity, action, from, to]);
  return <Card><div className="space-y-4"><div><p className="text-sm font-bold uppercase tracking-wide text-teal-700">Audit Logs</p><h2 className="text-2xl font-black">Riwayat audit tersentral</h2><p className="text-sm text-slate-500">Login/logout, token, import config, review, finalisasi, backup, restore, reset, dan export dicatat.</p></div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold text-amber-900">Pada versi localStorage, audit log masih dapat berubah jika seseorang memiliki akses perangkat/browser. Untuk produksi resmi, audit log harus disimpan di backend dengan proteksi perubahan manual.</div><div className="grid gap-3 md:grid-cols-6"><Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} /><Input type="date" value={to} onChange={(e) => setTo(e.target.value)} /><Select value={role} onChange={(e) => setRole(e.target.value)}><option value="">Semua role</option><option value="superadmin">Superadmin</option><option value="tester">Tester</option><option value="specialist">Spesialis</option><option value="participant">Participant</option><option value="system">System</option></Select><Select value={severity} onChange={(e) => setSeverity(e.target.value as AuditSeverity | '')}><option value="">Semua severity</option><option value="info">Info</option><option value="warning">Warning</option><option value="critical">Critical</option></Select><Input placeholder="Action" value={action} onChange={(e) => setAction(e.target.value)} /><Input placeholder="Cari peserta/token/resultId" value={query} onChange={(e) => setQuery(e.target.value)} /></div><div className="flex gap-2"><Button onClick={() => download('audit-logs.json', exportAuditLogs(filter, 'json'))}>Export JSON</Button><Button variant="secondary" onClick={() => download('audit-logs.csv', exportAuditLogs(filter, 'csv'), 'text/csv')}>Export CSV</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b"><th className="py-3">Waktu</th><th>Aktor</th><th>Role</th><th>Aksi</th><th>Target</th><th>Severity</th><th>Deskripsi</th><th>Metadata</th></tr></thead><tbody>{logs.map((log) => <tr key={log.logId} className="border-b border-slate-100 align-top dark:border-slate-800"><td className="py-3 text-xs">{new Date(log.timestamp).toLocaleString('id-ID')}</td><td>{log.actor.displayName || log.actor.username}</td><td>{log.actor.role || '-'}</td><td className="font-bold">{log.action}</td><td>{log.targetType} {log.targetId}</td><td>{log.severity}</td><td>{log.description}</td><td><details><summary className="cursor-pointer font-bold">Detail</summary><pre className="mt-2 max-w-xs whitespace-pre-wrap rounded bg-slate-100 p-2 text-xs dark:bg-slate-800">{JSON.stringify(log.metadata, null, 2)}</pre></details></td></tr>)}</tbody></table>{logs.length === 0 && <p className="py-8 text-center text-sm text-slate-500">Belum ada audit log.</p>}</div></div></Card>;
};
