import { useState } from 'react';
import { Button, Card, Input } from '../ui';
import { readAdminJson, writeAdminJson } from '../../utils/adminStorage';
import { writeAuditLog } from '../../utils/auditLog';
export interface ReportTemplate { templateId: string; templateName: string; version: string; isActive: boolean; sections: Array<{ sectionId: string; label: string; enabled: boolean; order: number }>; watermark: string; documentNumberFormat: string; footerText: string; createdAt: string; updatedAt: string; }
const key='sppg_mmpi2_report_template';
const defaults=['institution','identity','summary','chart','scores','rusdi','hubertus','comparison','summaryAnalysis','rh','redFlags','specialistNotes','conclusion','audit','signature'];
const defaultTemplate=():ReportTemplate=>({templateId:crypto.randomUUID(),templateName:'Template Operasional',version:'v1.0.0',isActive:true,sections:defaults.map((id,i)=>({sectionId:id,label:id,enabled:true,order:i+1})),watermark:'',documentNumberFormat:'SPPG/MMPI/{YYYY}/{SEQ}',footerText:'Hasil otomatis bukan diagnosis final.',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
export const ReportTemplateEditor=()=>{const [tpl,setTpl]=useState(readAdminJson<ReportTemplate>(key,defaultTemplate())); const save=()=>{writeAdminJson(key,{...tpl,updatedAt:new Date().toISOString()});writeAuditLog('Perubahan template laporan','reportTemplate',tpl.templateId,'Template laporan diperbarui.',{},'warning');}; return <Card><h2 className="text-2xl font-black">Editor template laporan</h2><div className="mt-4 grid gap-3"><Input value={tpl.templateName} onChange={(e)=>setTpl({...tpl,templateName:e.target.value})}/><Input value={tpl.watermark} placeholder="Watermark" onChange={(e)=>setTpl({...tpl,watermark:e.target.value})}/><Input value={tpl.documentNumberFormat} onChange={(e)=>setTpl({...tpl,documentNumberFormat:e.target.value})}/>{tpl.sections.sort((a,b)=>a.order-b.order).map((s)=><label key={s.sectionId} className="flex gap-3 rounded-2xl border p-3 text-sm font-bold"><input type="checkbox" checked={s.enabled} onChange={(e)=>setTpl({...tpl,sections:tpl.sections.map((x)=>x.sectionId===s.sectionId?{...x,enabled:e.target.checked}:x)})}/>{s.order}. {s.label}</label>)}<Button onClick={save}>Simpan template</Button></div></Card>}
