import { useMemo, useState } from 'react';
import type { AssessmentResult } from '../../types';
import { Button, Card, Input, Select, Badge } from '../ui';
import { downloadFile, exportResultJson, resultToCsv } from '../../utils/export';
import { saveAdminResults } from '../../utils/adminStorage';
import { EmptyState, PanelTitle } from './AdminCommon';

type EditableResult = AssessmentResult & { examinerNotes?: string; reviewedAt?: string; reportStatus?: string };

const value = (result: AssessmentResult, key: keyof AssessmentResult | string) => String((result as unknown as Record<string, unknown>)[key] ?? '');
const timeFromIso = (value?: string) => value ? new Date(value).toLocaleTimeString('id-ID', { hour12: false }) : '-';

export const ResultsManagementPanel = ({ results, onRefresh, openResult, toast }: { results: AssessmentResult[]; onRefresh: () => void; openResult: (result: AssessmentResult) => void; toast: (message: string, tone?: 'teal' | 'amber' | 'rose') => void }) => {
  const [filters, setFilters] = useState({ query: '', date: '', validity: '', unit: '', review: '' });
  const [detail, setDetail] = useState<EditableResult | null>(null);
  const filtered = useMemo(() => results.filter((result) => {
    const haystack = `${result.identity.name} ${result.identity.participantNumber ?? ''} ${result.identity.unit}`.toLowerCase();
    const validity = result.validityStatus?.status ?? 'unknown';
    const reviewed = Boolean(value(result, 'reviewedAt'));
    return (!filters.query || haystack.includes(filters.query.toLowerCase())) && (!filters.date || result.identity.assessmentDate === filters.date || result.submittedAt.startsWith(filters.date)) && (!filters.validity || validity === filters.validity) && (!filters.unit || result.identity.unit.toLowerCase().includes(filters.unit.toLowerCase())) && (!filters.review || (filters.review === 'reviewed' ? reviewed : !reviewed));
  }), [filters, results]);

  const updateResult = (updated: EditableResult) => { saveAdminResults(results.map((result) => result.id === updated.id ? updated : result)); onRefresh(); setDetail(updated); };
  const removeResult = (id: string) => { saveAdminResults(results.filter((result) => result.id !== id)); onRefresh(); toast('Hasil peserta dihapus.', 'amber'); };
  const exportCsv = (result: AssessmentResult) => downloadFile(`hasil-${result.identity.name || result.id}.csv`, resultToCsv([result]), 'text/csv;charset=utf-8');

  if (detail) return <Card><PanelTitle title="Detail hasil peserta" subtitle="Identitas, jawaban, skor mentah, T-score, status validitas, interpretasi otomatis, grafik data, dan catatan pemeriksa." status={<Button variant="ghost" onClick={() => setDetail(null)}>Kembali</Button>} />
    <div className="grid gap-4 lg:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-950"><h3 className="font-black">Identitas peserta</h3><dl className="mt-3 space-y-2 text-sm"><div><dt className="font-bold">Nama</dt><dd>{detail.identity.name}</dd></div><div><dt className="font-bold">Nomor peserta</dt><dd>{detail.identity.participantNumber ?? '-'}</dd></div><div><dt className="font-bold">Usia / gender</dt><dd>{detail.identity.age} / {detail.identity.gender}</dd></div><div><dt className="font-bold">Kesatuan</dt><dd>{detail.identity.unit}</dd></div><div><dt className="font-bold">Tanggal asesmen</dt><dd>{detail.identity.assessmentDate}</dd></div><div><dt className="font-bold">Tanggal/Jam mulai</dt><dd>{detail.startedDate ?? detail.startedAt?.slice(0, 10) ?? '-'} {detail.startedTime ?? timeFromIso(detail.startedAt)}</dd></div><div><dt className="font-bold">Tanggal/Jam selesai</dt><dd>{detail.submittedDate ?? detail.submittedAt.slice(0, 10)} {detail.submittedTime ?? timeFromIso(detail.submittedAt)}</dd></div><div><dt className="font-bold">Durasi</dt><dd>{detail.durationText ?? detail.durationLabel ?? '-'}</dd></div><div><dt className="font-bold">Total dijawab</dt><dd>{detail.answeredCount}/{detail.totalQuestions}</dd></div></dl></div><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-950"><h3 className="font-black">Status validitas</h3><p className="mt-2"><Badge tone={detail.validityStatus?.status === 'valid' ? 'teal' : detail.validityStatus?.status === 'invalid' ? 'rose' : 'amber'}>{detail.validityStatus?.label ?? 'Unknown'}</Badge></p><ul className="mt-3 list-disc pl-5 text-sm">{(detail.validityStatus?.reasons ?? ['Tidak ada catatan validitas.']).map((reason) => <li key={reason}>{reason}</li>)}</ul></div><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-950"><h3 className="font-black">Aksi laporan</h3><div className="mt-3 grid gap-2"><Button onClick={() => window.print()}>Cetak/PDF</Button><Button variant="secondary" onClick={() => exportResultJson(detail)}>Ekspor JSON</Button><Button variant="ghost" onClick={() => exportCsv(detail)}>Ekspor CSV</Button><Button variant="secondary" onClick={() => openResult(detail)}>Lihat laporan</Button></div></div></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><div><h3 className="font-black">Skor mentah dan T-score</h3><div className="mt-3 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr><th className="p-2">Skala</th><th className="p-2">Raw</th><th className="p-2">T-score</th><th className="p-2">Kategori</th></tr></thead><tbody>{detail.scores.map((score) => <tr key={score.scaleId} className="border-t border-slate-100 dark:border-slate-800"><td className="p-2">{score.code ?? score.scaleName}</td><td className="p-2">{score.rawScore}</td><td className="p-2">{score.tScore ?? 'Belum ada norma T-score'}</td><td className="p-2">{score.category}</td></tr>)}</tbody></table></div></div><div><h3 className="font-black">Interpretasi otomatis</h3><div className="mt-3 space-y-2 text-sm"><p>{detail.clinicalSummary ?? 'Interpretasi otomatis belum tersedia.'}</p>{(detail.recommendations ?? []).map((rec) => <p key={rec}>• {rec}</p>)}</div></div></div>
    <div className="mt-5"><h3 className="font-black">Jawaban tersimpan</h3><pre className="mt-3 max-h-56 overflow-auto rounded-2xl bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify(detail.answers, null, 2)}</pre></div>
    <div className="mt-5"><label className="text-sm font-bold">Catatan pemeriksa<textarea className="mt-2 min-h-32 w-full rounded-2xl border border-slate-200 bg-white p-4 text-sm dark:border-slate-700 dark:bg-slate-950" value={detail.examinerNotes ?? ''} onChange={(event) => setDetail({ ...detail, examinerNotes: event.target.value })} /></label><div className="mt-3 flex flex-wrap gap-3"><Button onClick={() => { updateResult(detail); toast('Catatan pemeriksa disimpan tanpa mengubah skor otomatis.', 'teal'); }}>Simpan catatan</Button><Button variant="secondary" onClick={() => { const updated = { ...detail, reviewedAt: new Date().toISOString(), status: 'Selesai' as const, reportStatus: 'Sudah ditelaah' }; updateResult(updated); toast('Hasil ditandai sudah ditelaah.', 'teal'); }}>Tandai sudah ditelaah</Button></div></div>
  </Card>;

  return <Card><PanelTitle title="Manajemen hasil peserta" subtitle="Data diambil dari sppg_mmpi2_results. Kelola laporan, ekspor, telaah, catatan pemeriksa, dan penghapusan hasil." />
    <div className="grid gap-3 md:grid-cols-5"><Input placeholder="Nama / nomor peserta" value={filters.query} onChange={(e) => setFilters({ ...filters, query: e.target.value })} /><Input type="date" value={filters.date} onChange={(e) => setFilters({ ...filters, date: e.target.value })} /><Select value={filters.validity} onChange={(e) => setFilters({ ...filters, validity: e.target.value })}><option value="">Semua validitas</option><option value="valid">Valid</option><option value="caution">Perhatian</option><option value="invalid">Invalid</option><option value="unknown">Belum diketahui</option></Select><Input placeholder="Kesatuan" value={filters.unit} onChange={(e) => setFilters({ ...filters, unit: e.target.value })} /><Select value={filters.review} onChange={(e) => setFilters({ ...filters, review: e.target.value })}><option value="">Semua telaah</option><option value="needs">Perlu telaah</option><option value="reviewed">Sudah ditelaah</option></Select></div>
    <div className="mt-5 overflow-x-auto">{filtered.length ? <table className="min-w-full text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr>{['Nama', 'Nomor peserta', 'Tanggal mulai', 'Jam mulai', 'Jam selesai', 'Durasi', 'Total soal', 'Total dijawab', 'Status pengerjaan', 'Status validitas', 'Status laporan', 'Waktu submit', 'Aksi'].map((head) => <th className="p-2" key={head}>{head}</th>)}</tr></thead><tbody>{filtered.map((result) => <tr key={result.id} className="border-t border-slate-100 dark:border-slate-800"><td className="p-2 font-bold">{result.identity.name}</td><td className="p-2">{result.identity.participantNumber ?? '-'}</td><td className="p-2">{result.startedDate ?? result.startedAt?.slice(0, 10) ?? '-'}</td><td className="p-2">{result.startedTime ?? timeFromIso(result.startedAt)}</td><td className="p-2">{result.submittedTime ?? timeFromIso(result.submittedAt)}</td><td className="p-2">{result.durationText ?? result.durationLabel ?? '-'}</td><td className="p-2">{result.totalQuestions}</td><td className="p-2">{result.answeredCount}</td><td className="p-2">{result.answeredCount >= result.totalQuestions ? 'Selesai lengkap' : 'Belum lengkap'}</td><td className="p-2">{result.validityStatus?.label ?? 'Belum diketahui'}</td><td className="p-2">{value(result, 'reviewedAt') ? 'Sudah ditelaah' : result.status}</td><td className="p-2">{new Date(result.submittedAt).toLocaleString('id-ID')}</td><td className="p-2"><div className="flex min-w-72 flex-wrap gap-2"><Button className="min-h-9 px-3 py-1" onClick={() => setDetail(result as EditableResult)}>Detail</Button><Button className="min-h-9 px-3 py-1" variant="secondary" onClick={() => openResult(result)}>Lihat laporan</Button><Button className="min-h-9 px-3 py-1" variant="ghost" onClick={() => window.print()}>Cetak/PDF</Button><Button className="min-h-9 px-3 py-1" variant="ghost" onClick={() => exportResultJson(result)}>JSON</Button><Button className="min-h-9 px-3 py-1" variant="ghost" onClick={() => exportCsv(result)}>CSV</Button><Button className="min-h-9 px-3 py-1" variant="secondary" onClick={() => { saveAdminResults(results.map((item) => item.id === result.id ? { ...item, reviewedAt: new Date().toISOString(), status: 'Selesai' as const, reportStatus: 'Sudah ditelaah' } : item)); onRefresh(); toast('Hasil ditandai sudah ditelaah.', 'teal'); }}>Telaah</Button><Button className="min-h-9 px-3 py-1" variant="danger" onClick={() => removeResult(result.id)}>Hapus</Button></div></td></tr>)}</tbody></table> : <EmptyState title="Belum ada hasil peserta sesuai filter" />}</div>
    <div className="mt-5 flex flex-wrap gap-3"><Button variant="secondary" disabled={!filtered.length} onClick={() => downloadFile('hasil-filtered.json', JSON.stringify(filtered, null, 2))}>Ekspor JSON Filter</Button><Button variant="secondary" disabled={!filtered.length} onClick={() => downloadFile('hasil-filtered.csv', resultToCsv(filtered), 'text/csv;charset=utf-8')}>Ekspor CSV Filter</Button></div>
  </Card>;
};
