import type { AssessmentResult, RHForm } from '../types';
import { Card, Button } from '../components/ui';
import { RHReportSection } from '../components/report/RHReportSection';
import { downloadFile } from '../utils/export';

export const RHReviewPage = ({ result, form, goBack }: { result?: AssessmentResult; form?: RHForm | null; goBack?: () => void }) => {
  const exportJson = () => form && downloadFile(`rh-${form.identity.fullName || form.resultId}.json`, JSON.stringify({ resultId: form.resultId, tokenId: form.tokenId, participant: result?.identity, statusMMPI: result?.assessment?.status ?? result?.status, statusRH: form.status, rh: form, redFlags: form.riskFlags, rhSubmittedAt: form.submittedAt, specialistNotes: result?.specialistReview }, null, 2));
  const exportCsv = () => form && downloadFile(`rh-${form.identity.fullName || form.resultId}.csv`, `resultId,tokenId,nama,statusMMPI,statusRH,redFlags,rhSubmittedAt,catatanSpesialis\n"${form.resultId}","${form.tokenId}","${form.identity.fullName}","${result?.assessment?.status ?? result?.status ?? ''}","${form.status}","${form.riskFlags.join('; ')}","${form.submittedAt}","${result?.specialistReview?.riskNotes ?? ''}"`, 'text/csv;charset=utf-8');
  return <div className="mx-auto max-w-6xl px-4 py-6"><Card className="mb-6 no-print"><h1 className="text-2xl font-black">Review RH Skrining</h1><p className="text-sm text-slate-500">Template print khusus Surat Pernyataan / Informed Consent dan Daftar Isian Riwayat Kesehatan.</p><div className="mt-4 flex flex-wrap gap-3"><Button onClick={exportJson} disabled={!form}>Export RH JSON</Button><Button variant="secondary" onClick={exportCsv} disabled={!form}>Export RH CSV</Button><Button variant="ghost" onClick={() => window.print()} disabled={!form}>Print RH</Button>{goBack && <Button variant="ghost" onClick={goBack}>Kembali</Button>}</div></Card><RHReportSection form={form} />{form && <Card><h2 className="text-xl font-black">Surat Pernyataan / Informed Consent</h2><div className="mt-4 grid gap-3 md:grid-cols-2 text-sm"><p><strong>No. Test:</strong> {form.consent.noTest}</p><p><strong>Nama:</strong> {form.consent.name}</p><p><strong>Tempat/tanggal lahir:</strong> {form.consent.birthPlaceDate}</p><p><strong>Kesatuan:</strong> {form.consent.unit}</p><p><strong>Alamat:</strong> {form.consent.homeAddress}</p><p><strong>No. telepon:</strong> {form.consent.phone}</p><p><strong>Institusi pemohon:</strong> {form.consent.institutionRequest}</p><p><strong>Dibuat di/tanggal:</strong> {form.consent.createdPlace}, {form.consent.createdDate}</p><p><strong>Yang membuat pernyataan:</strong> {form.consent.signatureName}</p></div></Card>}</div>;
};
