import type { RHForm } from '../../types';
import { Card } from '../ui';
import { RHRedFlagBadge } from '../rh/RHRedFlagBadge';
import { getRHRiskFlags } from '../../utils/rhRedFlags';

export const RHReportSection = ({ form }: { form?: RHForm | null }) => {
  if (!form) return <Card className="border-rose-200"><h2 className="text-xl font-black">Daftar Isian Riwayat Kesehatan</h2><p className="mt-3 font-semibold text-rose-700">RH Skrining belum lengkap. Laporan final tidak boleh dicetak tanpa RH.</p></Card>;
  const yesItems = form.healthHistory.items.filter((item) => item.answer === 'Ya');
  return <Card className="mb-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black">Daftar Isian Riwayat Kesehatan</h2><p className="text-sm font-semibold text-teal-700">Kesehatan Jiwa TNI Angkatan Udara</p></div><RHRedFlagBadge form={form} /></div><div className="mt-4 grid gap-3 md:grid-cols-3 text-sm"><p><strong>Nama:</strong><br />{form.identity.fullName || form.consent.name}</p><p><strong>No. Test:</strong><br />{form.consent.noTest}</p><p><strong>RH selesai pada:</strong><br />{form.submittedAt ? new Date(form.submittedAt).toLocaleString('id-ID') : '-'}</p><p><strong>Kondisi fisik:</strong><br />{form.healthHistory.physicalCondition}</p><p><strong>Kondisi mental:</strong><br />{form.healthHistory.mentalCondition}</p><p><strong>Obat rutin / tidur:</strong><br />{form.healthHistory.routineMedication.answer || '-'} / {form.healthHistory.sleepDifficulty.answer || '-'}</p></div><div className="mt-4"><h3 className="font-black">Ringkasan red flag RH</h3><ul className="mt-2 list-disc pl-5 text-sm leading-6">{getRHRiskFlags(form).map((flag) => <li key={flag}>{flag}</li>)}{!getRHRiskFlags(form).length && <li>Tidak ada red flag RH otomatis.</li>}</ul><p className="mt-3 rounded-2xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold text-amber-800">Temuan RH memerlukan konfirmasi melalui wawancara klinis oleh profesional berwenang.</p></div><details className="mt-4"><summary className="cursor-pointer font-bold">Lihat jawaban Ya dan catatan sosial</summary><ul className="mt-2 list-disc pl-5 text-sm leading-6">{yesItems.map((item) => <li key={item.no}>{item.no}. {item.complaint}: {item.note || '-'}</li>)}{!yesItems.length && <li>Tidak ada jawaban Ya pada 50 item.</li>}</ul><p className="mt-2 text-sm"><strong>Narkoba/zat adiktif:</strong> {form.socialHistory.substanceUseHistory || '-'} {form.socialHistory.substanceUseExplanation || ''}</p><p className="text-sm"><strong>Masalah hukum:</strong> {form.socialHistory.legalProblemHistory || '-'} {form.socialHistory.legalProblemExplanation || ''}</p></details></Card>;
};
