import { readAdminJson, writeAdminJson, ADMIN_STORAGE_KEYS } from './adminStorage';
import { loadAdminResults } from './adminStorage';
import { getActiveSessions } from './sessionMonitoring';
import { writeAuditLog } from './auditLog';
export interface OperationalAnomaly { anomalyId: string; type: string; severity: 'low' | 'medium' | 'high'; detectedAt: string; description: string; relatedIds: string[]; status: 'open' | 'acknowledged' | 'resolved'; acknowledgedBy: string; resolvedBy: string; }
export const ANOMALIES_KEY = 'sppg_mmpi2_operational_anomalies';
export const getAnomalyAlerts = () => readAdminJson<OperationalAnomaly[]>(ANOMALIES_KEY, []);
const save = (items: OperationalAnomaly[]) => writeAdminJson(ANOMALIES_KEY, items);
const anomaly = (type: string, severity: OperationalAnomaly['severity'], description: string, relatedIds: string[]): OperationalAnomaly => ({ anomalyId: crypto.randomUUID(), type, severity, detectedAt: new Date().toISOString(), description, relatedIds, status: 'open', acknowledgedBy: '', resolvedBy: '' });
export const detectOperationalAnomalies = () => { const results = loadAdminResults(); const sessions = getActiveSessions(); const tokens = readAdminJson<Array<{ tokenId: string; status: string }>>(ADMIN_STORAGE_KEYS.accessTokens, []); const found: OperationalAnomaly[] = []; const fast = results.filter((r) => (r.durationSeconds || 0) > 0 && (r.durationSeconds || 0) < 20 * 60); if (fast.length) found.push(anomaly('duration_too_fast', 'high', 'Ada peserta dengan durasi pengerjaan terlalu cepat.', fast.map((r) => r.id))); const slow = results.filter((r) => (r.durationSeconds || 0) > 4 * 60 * 60); if (slow.length) found.push(anomaly('duration_too_long', 'medium', 'Ada peserta dengan durasi pengerjaan terlalu lama.', slow.map((r) => r.id))); const idle = sessions.filter((s) => s.status === 'idle' || s.idleSeconds > 15 * 60); if (idle.length >= 3) found.push(anomaly('many_idle_sessions', 'medium', 'Banyak sesi idle dalam monitoring.', idle.map((s) => s.sessionId))); const revoked = tokens.filter((t) => t.status === 'revoked' || t.status === 'expired'); if (revoked.length >= 10) found.push(anomaly('token_failures', 'medium', 'Banyak token gagal/kedaluwarsa/revoked.', revoked.map((t) => t.tokenId))); const pending = results.filter((r) => r.specialistReview?.status === 'pending'); if (pending.length >= 10) found.push(anomaly('many_pending_reviews', 'medium', 'Banyak hasil menunggu scoring/review.', pending.map((r) => r.id))); const invalid = results.filter((r) => r.validityStatus?.status === 'invalid' || r.validityStatus?.status === 'caution'); if (invalid.length >= 5) found.push(anomaly('many_invalid_caution', 'high', 'Banyak laporan invalid/caution.', invalid.map((r) => r.id))); const existing = getAnomalyAlerts().filter((a) => a.status !== 'resolved'); save([...found, ...existing].slice(0, 200)); if (found.length) writeAuditLog('Detect operational anomalies', 'anomaly', 'batch', `${found.length} anomali operasional terdeteksi.`, { count: found.length }, 'warning'); return found; };
export const acknowledgeAnomaly = (anomalyId: string, by = '') => { const items = getAnomalyAlerts().map((a) => a.anomalyId === anomalyId ? { ...a, status: 'acknowledged' as const, acknowledgedBy: by } : a); save(items); };
export const resolveAnomaly = (anomalyId: string, by = '') => { const items = getAnomalyAlerts().map((a) => a.anomalyId === anomalyId ? { ...a, status: 'resolved' as const, resolvedBy: by } : a); save(items); };
