import type { AssessmentResult } from '../types';
import { loadAdminResults, saveAdminResults } from './adminStorage';
import { writeAuditLog } from './auditLog';
import { generateReportHash } from './reportHash';
import { isClinicalChecklistComplete } from '../components/review/clinicalChecklistUtils';
export interface FinalSignature { signedByUserId: string; signedByName: string; role: string; licenseNumber: string; signedAt: string; reportHash: string; signatureStatement: string; isLocked: boolean; }
export const signFinalReport = (resultId: string, user: { userId: string; displayName?: string; username?: string; role: string; licenseNumber?: string }) => { const results = loadAdminResults(); const result = results.find((item) => item.id === resultId) as (AssessmentResult & { finalSignature?: FinalSignature }) | undefined; if (!result) throw new Error('Hasil tidak ditemukan.'); if (!isClinicalChecklistComplete(result.clinicalFinalizationChecklist)) throw new Error('Checklist validitas klinis wajib lengkap sebelum finalisasi.'); const unsigned = { ...result, finalSignature: undefined }; const signature: FinalSignature = { signedByUserId: user.userId, signedByName: user.displayName || user.username || '', role: user.role, licenseNumber: user.licenseNumber || '', signedAt: new Date().toISOString(), reportHash: generateReportHash(unsigned), signatureStatement: 'Saya telah meninjau dan memfinalisasi laporan ini sesuai kewenangan.', isLocked: true }; result.finalSignature = signature; if (result.specialistReview) result.specialistReview = { ...result.specialistReview, status: 'finalized', isLocked: true }; saveAdminResults(results); writeAuditLog('Finalisasi laporan', 'result', resultId, 'Laporan final ditandatangani dan dikunci.', { reportHash: signature.reportHash }, 'critical'); return result; };
export const verifyReportHash = (resultId: string) => { const result = loadAdminResults().find((item) => item.id === resultId) as (AssessmentResult & { finalSignature?: FinalSignature }) | undefined; if (!result?.finalSignature) return { valid: false, message: 'Signature belum tersedia.' }; const current = generateReportHash({ ...result, finalSignature: undefined }); return { valid: current === result.finalSignature.reportHash, message: current === result.finalSignature.reportHash ? 'Hash valid.' : 'Hash berbeda dari signature.', currentHash: current, signedHash: result.finalSignature.reportHash }; };
export const unlockFinalReportBySuperadmin = (resultId: string, reason: string) => { const results = loadAdminResults(); const result = results.find((item) => item.id === resultId) as (AssessmentResult & { finalSignature?: FinalSignature }) | undefined; if (!result?.finalSignature) throw new Error('Signature belum tersedia.'); result.finalSignature.isLocked = false; if (result.specialistReview) result.specialistReview.isLocked = false; saveAdminResults(results); writeAuditLog('Unlock laporan oleh superadmin', 'result', resultId, 'Laporan final dibuka oleh Superadmin.', { reason }, 'critical'); return result; };
export { generateReportHash } from './reportHash';
