import type { AssessmentResult } from '../types';
import { loadAdminResults, saveAdminResults } from './adminStorage';
import { writeAuditLog } from './auditLog';
export type ReportWorkflowStatus = 'draft_result' | 'pending_scoring' | 'awaiting_rh' | 'awaiting_operator_verification' | 'awaiting_specialist_review' | 'needs_revision' | 'awaiting_final_approval' | 'finalized' | 'archived';
export interface WorkflowState { status: ReportWorkflowStatus; operatorVerifiedBy: string; operatorVerifiedAt: string; specialistReviewedBy: string; specialistReviewedAt: string; finalApprovedBy: string; finalApprovedAt: string; revisionNotes: Array<{ by: string; at: string; note: string }>; history: Array<{ by: string; at: string; from: string; to: string; note: string }>; }
export const defaultWorkflow = (status: ReportWorkflowStatus = 'awaiting_specialist_review'): WorkflowState => ({ status, operatorVerifiedBy: '', operatorVerifiedAt: '', specialistReviewedBy: '', specialistReviewedAt: '', finalApprovedBy: '', finalApprovedAt: '', revisionNotes: [], history: [] });
export const ensureWorkflow = (result: AssessmentResult) => (result.workflow as WorkflowState | undefined) ?? defaultWorkflow(result.rhCompleted ? 'awaiting_operator_verification' : 'awaiting_rh');
export const updateWorkflowStatus = (resultId: string, status: ReportWorkflowStatus, by = '', note = '') => { const results = loadAdminResults(); const result = results.find((it) => it.id === resultId); if (!result) throw new Error('Hasil tidak ditemukan.'); const workflow = ensureWorkflow(result); const from = workflow.status; workflow.status = status; workflow.history = [...workflow.history, { by, at: new Date().toISOString(), from, to: status, note }]; (result as AssessmentResult & { workflow: WorkflowState }).workflow = workflow; saveAdminResults(results); writeAuditLog('Update review workflow', 'result', resultId, `Workflow berubah dari ${from} ke ${status}.`, { note }, 'info'); return result; };
export const addRevisionNote = (resultId: string, by: string, note: string) => { const results = loadAdminResults(); const result = results.find((it) => it.id === resultId); if (!result) throw new Error('Hasil tidak ditemukan.'); const workflow = ensureWorkflow(result); workflow.status = 'needs_revision'; workflow.revisionNotes.push({ by, at: new Date().toISOString(), note }); (result as AssessmentResult & { workflow: WorkflowState }).workflow = workflow; saveAdminResults(results); writeAuditLog('Add revision note', 'result', resultId, 'Catatan revisi spesialis ditambahkan.', { note }, 'warning'); return result; };
export const saveClinicalChecklistForResult = (resultId: string, checklist: import('../types').ClinicalFinalizationChecklist) => { const results = loadAdminResults(); const result = results.find((it) => it.id === resultId); if (!result) throw new Error('Hasil tidak ditemukan.'); result.clinicalFinalizationChecklist = checklist; saveAdminResults(results); writeAuditLog('Save clinical checklist', 'result', resultId, 'Checklist validitas klinis disimpan.', { complete: Object.values(checklist).filter(Boolean).length }, 'info'); return result; };
