import type { RHForm } from '../types';
import { RED_FLAG_HEALTH_NUMBERS } from './rhRedFlags';

export type RHSectionId = 'consent' | 'identity' | 'health' | 'education' | 'work' | 'family' | 'social' | 'review';
export interface RHValidationResult { complete: boolean; missing: string[]; sectionMissing: Record<RHSectionId, string[]>; percent: number }
const filled = (value?: string | boolean) => typeof value === 'boolean' ? value : Boolean(value?.trim());
const yes = (value?: string) => value === 'Ya';

export const validateRHForm = (form: RHForm): RHValidationResult => {
  const sectionMissing: RHValidationResult['sectionMissing'] = { consent: [], identity: [], health: [], education: [], work: [], family: [], social: [], review: [] };
  const req = (section: RHSectionId, ok: boolean, label: string) => { if (!ok) sectionMissing[section].push(label); };
  req('consent', filled(form.consent.noTest), 'No. Test'); req('consent', filled(form.consent.name), 'Nama pada surat pernyataan'); req('consent', filled(form.consent.birthPlaceDate), 'Tempat / tanggal lahir'); req('consent', filled(form.consent.unit), 'Kesatuan'); req('consent', filled(form.consent.institutionRequest), 'Nama institusi pemohon'); req('consent', filled(form.consent.createdPlace), 'Dibuat di'); req('consent', filled(form.consent.createdDate), 'Pada tanggal'); req('consent', filled(form.consent.signatureName), 'Nama pembuat pernyataan'); req('consent', form.consent.statementAccepted, 'Checkbox persetujuan');
  ['fullName', 'birthPlace', 'birthDateInput', 'homeAddress', 'phone', 'religion', 'gender', 'examPurpose'].forEach((key) => req('identity', filled(form.identity[key as keyof RHForm['identity']]), `Identitas: ${key}`));
  form.healthHistory.items.forEach((item) => { req('health', item.answer === 'Ya' || item.answer === 'Tidak', `Item ${item.no} belum dijawab`); if (item.answer === 'Ya' && RED_FLAG_HEALTH_NUMBERS.includes(item.no)) req('health', filled(item.note), `Keterangan item red flag ${item.no}`); if (item.no === 50 && item.answer === 'Ya') ['date', 'place', 'duration', 'disease'].forEach((key) => req('health', filled(item.hospitalization?.[key as 'date' | 'place' | 'duration' | 'disease']), `Detail rawat inap: ${key}`)); });
  req('health', filled(form.healthHistory.physicalCondition), 'Kondisi kesehatan fisik'); req('health', filled(form.healthHistory.mentalCondition), 'Kondisi kesehatan mental'); req('health', filled(form.healthHistory.routineMedication.answer), 'Pertanyaan obat rutin'); if (yes(form.healthHistory.routineMedication.answer)) { req('health', filled(form.healthHistory.routineMedication.medicineType), 'Jenis obat rutin'); req('health', filled(form.healthHistory.routineMedication.startDate), 'Mulai minum obat'); } req('health', filled(form.healthHistory.sleepDifficulty.answer), 'Pertanyaan kesulitan tidur'); if (yes(form.healthHistory.sleepDifficulty.answer)) req('health', filled(form.healthHistory.sleepDifficulty.needsMedication), 'Pertanyaan bantuan obat tidur');
  req('education', form.educationHistory.some((row) => filled(row.schoolName) || filled(row.years) || filled(row.graduationStatus)), 'Minimal pendidikan terakhir');
  req('work', filled(form.workQuestions.hasWorkDifficulty), 'Pertanyaan kesulitan bekerja'); if (yes(form.workQuestions.hasWorkDifficulty)) req('work', filled(form.workQuestions.workDifficultyExplanation), 'Penjelasan kesulitan bekerja'); req('work', filled(form.workQuestions.positiveAspects), 'Aspek positif'); req('work', filled(form.workQuestions.negativeAspects), 'Aspek negatif'); req('work', filled(form.workQuestions.willingToWork), 'Kesediaan bekerja'); req('work', filled(form.workQuestions.willingToWorkExplanation), 'Penjelasan kesediaan bekerja');
  req('family', filled(form.familyHistory.livingWithFamily), 'Pertanyaan tinggal bersama keluarga'); if (form.familyHistory.livingWithFamily === 'Tidak') req('family', filled(form.familyHistory.livingWithFamilyReason), 'Alasan tidak tinggal bersama keluarga'); req('family', filled(form.familyHistory.hasFamilyProblem), 'Pertanyaan masalah keluarga'); if (yes(form.familyHistory.hasFamilyProblem)) req('family', filled(form.familyHistory.familyProblemExplanation), 'Penjelasan masalah keluarga'); req('family', filled(form.familyHistory.spouseSupportsCareer), 'Dukungan pasangan/keluarga'); if (form.familyHistory.spouseSupportsCareer === 'Tidak') req('family', filled(form.familyHistory.spouseSupportExplanation), 'Alasan dukungan pasangan/keluarga');
  req('social', filled(form.socialHistory.hasSeriousProblem), 'Pertanyaan persoalan berat'); if (yes(form.socialHistory.hasSeriousProblem)) { req('social', filled(form.socialHistory.seriousProblemExplanation), 'Uraian persoalan berat'); req('social', filled(form.socialHistory.receivedTreatmentForProblem), 'Berobat untuk persoalan berat'); } req('social', filled(form.socialHistory.makingFriendsStyle), 'Cara mendapatkan kawan'); req('social', filled(form.socialHistory.difficultyWithFamily), 'Kesulitan pergaulan keluarga'); req('social', filled(form.socialHistory.difficultyWithSchoolFriends), 'Kesulitan teman sekolah/lingkungan'); req('social', filled(form.socialHistory.difficultyWithCoworkers), 'Kesulitan rekan kerja'); req('social', filled(form.socialHistory.freeTimeActivities), 'Waktu senggang'); req('social', filled(form.socialHistory.substanceUseHistory), 'Riwayat narkoba/zat adiktif'); if (yes(form.socialHistory.substanceUseHistory)) req('social', filled(form.socialHistory.substanceUseExplanation), 'Keterangan narkoba/zat adiktif'); req('social', filled(form.socialHistory.legalProblemHistory), 'Riwayat masalah hukum'); if (yes(form.socialHistory.legalProblemHistory)) req('social', filled(form.socialHistory.legalProblemExplanation), 'Keterangan masalah hukum');
  const missing = Object.values(sectionMissing).flat();
  const totalChecks = 84;
  return { complete: missing.length === 0, missing, sectionMissing, percent: Math.max(0, Math.min(100, Math.round(((totalChecks - missing.length) / totalChecks) * 100))) };
};
