import type { CurrentSession } from '../types';
import { readAdminJson, writeAdminJson } from './adminStorage';
import { writeAuditLog } from './auditLog';
export type SessionMonitorStatus = 'not_started' | 'mmpi_in_progress' | 'mmpi_completed_pending_rh' | 'rh_in_progress' | 'completed' | 'interrupted' | 'idle';
export interface MonitoredSession { sessionId: string; tokenId: string; participantName: string; participantNumber: string; status: SessionMonitorStatus; answeredCount: number; totalItems: number; progressPercent: number; startedAt: string; lastActivityAt: string; durationSeconds: number; idleSeconds: number; completedAt: string; needsOperatorHelp: boolean; }
export const SESSION_MONITORING_KEY = 'sppg_mmpi2_session_monitoring';
export const calculateSessionProgress = (answeredCount = 0, totalItems = 567) => Math.round((answeredCount / Math.max(totalItems, 1)) * 100);
export const getActiveSessions = () => readAdminJson<MonitoredSession[]>(SESSION_MONITORING_KEY, []);
const save = (sessions: MonitoredSession[]) => writeAdminJson(SESSION_MONITORING_KEY, sessions);
export const updateSessionMonitoring = (session: CurrentSession, totalItems = 567) => { const now = new Date().toISOString(); const startedAt = session.startedAt || now; const answeredCount = Object.keys(session.answers || {}).length; const item: MonitoredSession = { sessionId: session.sessionId || session.id, tokenId: session.tokenId || '', participantName: session.identity?.name || session.participant?.name || '', participantNumber: session.identity?.participantNumber || session.participant?.participantNumber || '', status: (session.mmpiStatus === 'completed' || session.rhStatus === 'completed' ? 'completed' : session.mmpiStatus || 'mmpi_in_progress') as SessionMonitorStatus, answeredCount, totalItems, progressPercent: calculateSessionProgress(answeredCount, totalItems), startedAt, lastActivityAt: session.lastSavedAt || session.updatedAt || now, durationSeconds: Math.floor((Date.now() - new Date(startedAt).getTime()) / 1000), idleSeconds: Math.floor((Date.now() - new Date(session.lastSavedAt || session.updatedAt || now).getTime()) / 1000), completedAt: session.rhStatus === 'completed' ? now : '', needsOperatorHelp: false }; const sessions = getActiveSessions().filter((it) => it.sessionId !== item.sessionId); save([item, ...sessions]); return item; };
export const markSessionIdle = (sessionId: string) => { const sessions = getActiveSessions().map((it) => it.sessionId === sessionId ? { ...it, status: 'idle' as const, needsOperatorHelp: true } : it); save(sessions); writeAuditLog('Session idle', 'session', sessionId, 'Sesi peserta idle terlalu lama.', {}, 'warning'); };
export const markSessionInterrupted = (sessionId: string) => { const sessions = getActiveSessions().map((it) => it.sessionId === sessionId ? { ...it, status: 'interrupted' as const, needsOperatorHelp: true } : it); save(sessions); writeAuditLog('Session interrupted', 'session', sessionId, 'Sesi peserta terputus.', {}, 'warning'); };
export const getOperatorMonitoringStats = () => { const s = getActiveSessions(); return { total: s.length, notStarted: s.filter((x) => x.status === 'not_started').length, inProgress: s.filter((x) => x.status === 'mmpi_in_progress' || x.status === 'rh_in_progress').length, pendingRh: s.filter((x) => x.status === 'mmpi_completed_pending_rh').length, completed: s.filter((x) => x.status === 'completed').length, idle: s.filter((x) => x.status === 'idle').length, interrupted: s.filter((x) => x.status === 'interrupted').length, needsHelp: s.filter((x) => x.needsOperatorHelp).length }; };
