import type { AccessToken } from '../types';
import { ADMIN_STORAGE_KEYS, readAdminJson, writeAdminJson } from './adminStorage';
import { writeAuditLog } from './auditLog';
export interface TokenBatch { batchId: string; batchName: string; createdAt: string; expiresAt: string; createdBy: string; tokenCount: number; status: 'active' | 'expired' | 'revoked'; notes: string; }
export interface AdvancedAccessToken extends AccessToken { batchId?: string; singleActiveSessionOnly?: boolean; activeSessionId?: string | null; deviceHistory?: Array<{ at: string; userAgent: string; note: string }>; revokedAt?: string; revokedBy?: string; }
export const TOKEN_BATCHES_KEY = 'sppg_mmpi2_token_batches';
export const getTokenBatches = () => readAdminJson<TokenBatch[]>(TOKEN_BATCHES_KEY, []);
export const getAdvancedTokens = () => readAdminJson<AdvancedAccessToken[]>(ADMIN_STORAGE_KEYS.accessTokens, []);
const randomCode = () => Math.random().toString(36).slice(2, 8).toUpperCase();
export const generateTokenBatch = (batchName: string, tokenCount: number, expiresAt: string, createdBy = '', notes = '') => { const batch: TokenBatch = { batchId: crypto.randomUUID(), batchName, createdAt: new Date().toISOString(), expiresAt, createdBy, tokenCount, status: 'active', notes }; const tokens = Array.from({ length: tokenCount }, (): AdvancedAccessToken => ({ tokenId: crypto.randomUUID(), batchId: batch.batchId, token: `TNI-${randomCode()}`, uniqueKey: randomCode(), status: 'unused', maxAttempts: 1, usedAttempts: 0, singleActiveSessionOnly: true, activeSessionId: null, deviceHistory: [], createdAt: batch.createdAt, expiresAt })); writeAdminJson(TOKEN_BATCHES_KEY, [batch, ...getTokenBatches()]); writeAdminJson(ADMIN_STORAGE_KEYS.accessTokens, [...tokens, ...getAdvancedTokens()]); writeAuditLog('Generate token batch', 'tokenBatch', batch.batchId, `Generate ${tokenCount} token.`, { batchName }, 'info'); return { batch, tokens }; };
export const revokeBatchToken = (batchId: string, revokedBy = '') => { writeAdminJson(TOKEN_BATCHES_KEY, getTokenBatches().map((b) => b.batchId === batchId ? { ...b, status: 'revoked' } : b)); writeAdminJson(ADMIN_STORAGE_KEYS.accessTokens, getAdvancedTokens().map((t) => t.batchId === batchId ? { ...t, status: 'revoked', revokedAt: new Date().toISOString(), revokedBy } : t)); writeAuditLog('Revoke token batch', 'tokenBatch', batchId, 'Revoke massal token batch.', {}, 'critical'); };
export const resetToken = (tokenId: string) => { const tokens = getAdvancedTokens().map((t) => t.tokenId === tokenId ? { ...t, status: 'unused', usedAttempts: 0, activeSessionId: null, startedAt: null, completedAt: null, resultId: null } : t); writeAdminJson(ADMIN_STORAGE_KEYS.accessTokens, tokens); writeAuditLog('Reset token', 'token', tokenId, 'Token direset untuk dipakai ulang.', {}, 'warning'); };
export const exportTokenBatch = (batchId: string) => JSON.stringify({ batch: getTokenBatches().find((b) => b.batchId === batchId), tokens: getAdvancedTokens().filter((t) => t.batchId === batchId) }, null, 2);
